<<: !include secrets.yaml

esphome:
  name: beer
  platform: esp8266
  board: nodemcu

# Enable logging
logger:
  level: DEBUG

captive_portal:

web_server:
  port: 80
  local: true
  auth:
    username: admin
    password: !secret web_server_password

dallas:
  - pin: D7
    update_interval: 10s

sensor:
  - platform: dallas
    id: temp_hlt_tank
    address: 0x14000009079e2828
    name: "HLT Tank"
  - platform: dallas
    id: temp_hlt_herms_out
    address: 0x4700000907f6a128
    name: "HLT HERMS Out"
  - platform: dallas
    id: temp_fermentation_tank
    address: 0xc90315546ce1ff28
    name: "Fermentation Tank"
  - platform: dallas
    id: temp_mash_tun
    address: 0x4d0315543d57ff28
    name: "Mash Tun"

switch:
  - platform: gpio
    pin: D6
    name: "HLT Pump"
    id: hlt_pump
    restore_mode: ALWAYS_OFF
    inverted: true
  - platform: gpio
    pin: D5
    name: "Mash Pump"
    id: mash_pump
    restore_mode: ALWAYS_OFF
    inverted: true
  - platform: gpio
    pin: D4
    name: "Boiler Pump"
    id: boiler_pump
    restore_mode: ALWAYS_OFF
    inverted: true
  - platform: gpio
    pin: D3
    name: "Extractor Fan"
    id: extractor_fan
    restore_mode: ALWAYS_OFF
    inverted: true
  - platform: gpio
    pin: D0
    name: "Fermenter Heater"
    id: fermenter_heater
    restore_mode: ALWAYS_OFF
climate:
  - platform: pid
    id: hlt_pid
    name: "HLT PID"
    sensor: temp_hlt_tank
    default_target_temperature: 1°C
    heat_output: hlt_heater
    control_parameters:
      kp: 0.49460
      ki: 0.00487
      kd: 12.56301
    visual:
      max_temperature: 80 °C
      temperature_step: 1 °C
  - platform: thermostat
    name: "Fermentation Controller"
    id: fermentation_controller
    sensor: temp_fermentation_tank
    default_target_temperature_low: 18 °C
    default_target_temperature_high: 20 °C
    min_cooling_off_time: 30s
    min_cooling_run_time: 300s
    min_heating_off_time: 30s
    min_heating_run_time: 30s
    min_idle_time: 30s
    cool_action:
      - switch.turn_off: fermenter_heater
    heat_action:
      - switch.turn_on: fermenter_heater
    idle_action:
      - switch.turn_off: fermenter_heater

output:
  - platform: slow_pwm
    pin: D2
    id: boiler_heater
    period: 2s
  - platform: esp8266_pwm
    pin: D1
    id: hlt_heater

fan:
  - platform: speed
    output: boiler_heater
    id: boiler_duty
    name: "Boiler Heater"
